name: MaskPlugin
version: 1.0-SNAPSHOT
main: me.exodian.maskplugin.MaskPlugin
api-version: 1.13
authors: [SamPom100]
description: Hides a player's nametag upon donning the mask

permissions:
  invishelm.use:
    description: Permission to be given an invisibility helm
    default: false



commands:
  helm:
    description: Gives you the Invisibility Helm!
    usage: /helm
    permission: invishelm.use
    permission-message: You don't have permission to do that